jobs:
  - name: landing-pages_runCI
    type: runCI
    steps:
      - IN: website_s3_params

  - name: website_deploy_to_prod
    type: runSh
    steps:
      - IN: landing-pages_runCI
        switch: off
      - IN: website_s3_params
      - IN: website_s3_prod_params
      - TASK:
        # build page, copy to production bucket and invalidate CloudFront distribution
        - script: S3_BUCKET=$PRODUCTION_BUCKET $LANDINGPAGES_RUNCI_STATE/build.sh
